/** 
 * QQ:1598773037
 * copyright(c) 2023 Swallows_
 * 未经允许禁止使用于任何地方
 * Prohibit use anywhere without permission
 */

#reloadable
#priority 9999
#loader crafttweaker reloadable

import crafttweaker.item.IItemStack;


for Item in getRemoveItems_CHANGE() {
    recipes.remove(Item);
}

for Item in getRemoveItems_BAN() {
    recipes.remove(Item);
    Item.addTooltip("§c该物品已被禁用§r");
}


//////////模块化:社区版//////////
recipes.removeByMod("modularmachinery");
///////////FTB任务//////////
recipes.removeByMod("modularmachinery");
///////////合成拓展//////////
recipes.removeByMod("extendedcrafting");

function getRemoveItems_BAN() as IItemStack[] {
    val RemoveItems_BAN as IItemStack[] = [
        <minecraft:minecart>,
        <minecraft:chest_minecart>,
        <minecraft:furnace_minecart>,
        <minecraft:tnt_minecart>,
        <minecraft:hopper_minecart>,
        <minecraft:command_block_minecart>,
        <botania:poolminecart>,
        <minecraft:command_block>,
        <minecraft:repeating_command_block>,
        <minecraft:chain_command_block>,
        <avaritiarecipemaker:vanillarecipemakerblock>,
        <avaritiarecipemaker:avaritiarecipemakerblock>,
        <ironchest:iron_gold_shulker_upgrade>,
        <ironchest:gold_diamond_shulker_upgrade>,
        <ironchest:copper_silver_shulker_upgrade>,
        <ironchest:silver_gold_shulker_upgrade>,
        <ironchest:copper_iron_shulker_upgrade>,
        <ironchest:diamond_crystal_shulker_upgrade>,
        <ironchest:vanilla_iron_shulker_upgrade>,
        <ironchest:vanilla_copper_shulker_upgrade>,
        <ironchest:diamond_obsidian_shulker_upgrade>,
        <ironchest:diamond_crystal_chest_upgrade>,
        <ironchest:iron_chest:5>,
        <ironchest:iron_shulker_box_white>,
        <ironchest:iron_shulker_box_white:1>,
        <ironchest:iron_shulker_box_white:2>,
        <ironchest:iron_shulker_box_white:3>,
        <ironchest:iron_shulker_box_white:4>,
        <ironchest:iron_shulker_box_white:5>,
        <ironchest:iron_shulker_box_white:6>,
        <ironchest:iron_shulker_box_orange>,
        <ironchest:iron_shulker_box_orange:1>,
        <ironchest:iron_shulker_box_orange:2>,
        <ironchest:iron_shulker_box_orange:3>,
        <ironchest:iron_shulker_box_orange:4>,
        <ironchest:iron_shulker_box_orange:5>,
        <ironchest:iron_shulker_box_orange:6>,
        <ironchest:iron_shulker_box_magenta>,
        <ironchest:iron_shulker_box_magenta:1>,
        <ironchest:iron_shulker_box_magenta:2>,
        <ironchest:iron_shulker_box_magenta:3>,
        <ironchest:iron_shulker_box_magenta:4>,
        <ironchest:iron_shulker_box_magenta:5>,
        <ironchest:iron_shulker_box_magenta:6>,
        <ironchest:iron_shulker_box_light_blue>,
        <ironchest:iron_shulker_box_light_blue:1>,
        <ironchest:iron_shulker_box_light_blue:2>,
        <ironchest:iron_shulker_box_light_blue:3>,
        <ironchest:iron_shulker_box_light_blue:4>,
        <ironchest:iron_shulker_box_light_blue:5>,
        <ironchest:iron_shulker_box_light_blue:6>,
        <ironchest:iron_shulker_box_yellow>,
        <ironchest:iron_shulker_box_yellow:1>,
        <ironchest:iron_shulker_box_yellow:2>,
        <ironchest:iron_shulker_box_yellow:3>,
        <ironchest:iron_shulker_box_yellow:4>,
        <ironchest:iron_shulker_box_yellow:5>,
        <ironchest:iron_shulker_box_yellow:6>,
        <ironchest:iron_shulker_box_lime>,
        <ironchest:iron_shulker_box_lime:1>,
        <ironchest:iron_shulker_box_lime:2>,
        <ironchest:iron_shulker_box_lime:3>,
        <ironchest:iron_shulker_box_lime:4>,
        <ironchest:iron_shulker_box_lime:5>,
        <ironchest:iron_shulker_box_lime:6>,
        <ironchest:iron_shulker_box_pink>,
        <ironchest:iron_shulker_box_pink:1>,
        <ironchest:iron_shulker_box_pink:2>,
        <ironchest:iron_shulker_box_pink:3>,
        <ironchest:iron_shulker_box_pink:4>,
        <ironchest:iron_shulker_box_pink:5>,
        <ironchest:iron_shulker_box_pink:6>,
        <ironchest:iron_shulker_box_gray>,
        <ironchest:iron_shulker_box_gray:1>,
        <ironchest:iron_shulker_box_gray:2>,
        <ironchest:iron_shulker_box_gray:3>,
        <ironchest:iron_shulker_box_gray:4>,
        <ironchest:iron_shulker_box_gray:5>,
        <ironchest:iron_shulker_box_gray:6>,
        <ironchest:iron_shulker_box_silver>,
        <ironchest:iron_shulker_box_silver:1>,
        <ironchest:iron_shulker_box_silver:2>,
        <ironchest:iron_shulker_box_silver:3>,
        <ironchest:iron_shulker_box_silver:4>,
        <ironchest:iron_shulker_box_silver:5>,
        <ironchest:iron_shulker_box_silver:6>,
        <ironchest:iron_shulker_box_cyan>,
        <ironchest:iron_shulker_box_cyan:1>,
        <ironchest:iron_shulker_box_cyan:2>,
        <ironchest:iron_shulker_box_cyan:3>,
        <ironchest:iron_shulker_box_cyan:4>,
        <ironchest:iron_shulker_box_cyan:5>,
        <ironchest:iron_shulker_box_cyan:6>,
        <ironchest:iron_shulker_box_purple>,
        <ironchest:iron_shulker_box_purple:1>,
        <ironchest:iron_shulker_box_purple:2>,
        <ironchest:iron_shulker_box_purple:3>,
        <ironchest:iron_shulker_box_purple:4>,
        <ironchest:iron_shulker_box_purple:5>,
        <ironchest:iron_shulker_box_purple:6>,
        <ironchest:iron_shulker_box_blue>,
        <ironchest:iron_shulker_box_blue:1>,
        <ironchest:iron_shulker_box_blue:2>,
        <ironchest:iron_shulker_box_blue:3>,
        <ironchest:iron_shulker_box_blue:4>,
        <ironchest:iron_shulker_box_blue:5>,
        <ironchest:iron_shulker_box_blue:6>,
        <ironchest:iron_shulker_box_brown>,
        <ironchest:iron_shulker_box_brown:1>,
        <ironchest:iron_shulker_box_brown:2>,
        <ironchest:iron_shulker_box_brown:3>,
        <ironchest:iron_shulker_box_brown:4>,
        <ironchest:iron_shulker_box_brown:5>,
        <ironchest:iron_shulker_box_brown:6>,
        <ironchest:iron_shulker_box_green>,
        <ironchest:iron_shulker_box_green:1>,
        <ironchest:iron_shulker_box_green:2>,
        <ironchest:iron_shulker_box_green:3>,
        <ironchest:iron_shulker_box_green:4>,
        <ironchest:iron_shulker_box_green:5>,
        <ironchest:iron_shulker_box_green:6>,
        <ironchest:iron_shulker_box_red>,
        <ironchest:iron_shulker_box_red:1>,
        <ironchest:iron_shulker_box_red:2>,
        <ironchest:iron_shulker_box_red:3>,
        <ironchest:iron_shulker_box_red:4>,
        <ironchest:iron_shulker_box_red:5>,
        <ironchest:iron_shulker_box_red:6>,
        <ironchest:iron_shulker_box_black>,
        <ironchest:iron_shulker_box_black:1>,
        <ironchest:iron_shulker_box_black:2>,
        <ironchest:iron_shulker_box_black:3>,
        <ironchest:iron_shulker_box_black:4>,
        <ironchest:iron_shulker_box_black:5>,
        <ironchest:iron_shulker_box_black:6>,
        <minecraft:observer>,
        <minecraft:white_shulker_box>,
        <minecraft:orange_shulker_box>,
        <minecraft:magenta_shulker_box>,
        <minecraft:light_blue_shulker_box>,
        <minecraft:yellow_shulker_box>,
        <minecraft:lime_shulker_box>,
        <minecraft:pink_shulker_box>,
        <minecraft:gray_shulker_box>,
        <minecraft:silver_shulker_box>,
        <minecraft:cyan_shulker_box>,
        <minecraft:blue_shulker_box>,
        <minecraft:brown_shulker_box>,
        <minecraft:red_shulker_box>,
        <minecraft:black_shulker_box>,
        <minecraft:purple_shulker_box>,
        <minecraft:green_shulker_box>,
        <minecraft:item_frame>,
        <tconstruct:fancy_frame>,
        <tconstruct:fancy_frame:1>,
        <tconstruct:fancy_frame:2>,
        <tconstruct:fancy_frame:3>,
        <tconstruct:fancy_frame:4>,
        <tconstruct:fancy_frame:5>,
        <tconstruct:fancy_frame:6>,
        <minecraft:golden_rail>,
        <enderio:block_exit_rail>,
        <minecraft:detector_rail>,
        <minecraft:rail>,
        <minecraft:activator_rail>,
        <ic2:mining_laser>,
        <ic2:tool_box>,
        <ic2:containment_box>,
        <ic2:dynamite>,
        <ic2:dynamite_sticky>,
        <ic2:remote>,
        <gravisuite:vajra>,
        <draconicevolution:entity_detector>,
        <draconicevolution:entity_detector:1>,
        <draconicevolution:magnet>,
        <draconicevolution:magnet:1>,
        <draconicevolution:portal>,
        <mekanism:machineblock3:5>,
        <mekanism:machineblock3>,
        <mekanism:transmitter:1>,
        <mekanism:transmitter:2>,
        <mekanism:transmitter:3>,
        <mekanism:transmitter:4>,
        <mekanism:transmitter:5>,
        <mekanism:transmitter:6>,
        <mekanism:cardboardbox>,
        <mekanism:machineblock:4>,
        <mekanism:basicblock:7>,
        <mekanism:basicblock:6>,
        <mekanism:machineblock:11>,
        <mekanism:robit>,
        <mekanism:flamethrower>,

    ];
    return RemoveItems_BAN;
}

function getRemoveItems_CHANGE() as IItemStack[] {
    val RemoveItems_CHANGE as IItemStack[] = [
        <ic2:te:52>,
        <draconicevolution:celestial_manipulator>
    ];
    return RemoveItems_CHANGE;
}